name = "ADOLC"
uuid = "a7293fd6-5c8a-477e-b6cc-312e3ac044ef"
authors = ["Tim Siebert <tim.siebert96@outlook.com>", "Jürgen Fuhrmann"]
version = "2.0.0"

[deps]
ADOLC_jll = "5f481b30-e4a3-563b-890b-c343462061b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
ADOLC_jll = "2.0.0"
LinearAlgebra = "1.9"
SpecialFunctions = "2.4"
