name = "ADOLC"
uuid = "a7293fd6-5c8a-477e-b6cc-312e3ac044ef"
authors = ["Tim Siebert <tim.siebert96@outlook.com>", "Jürgen Fuhrmann"]
version = "1.1.0"

[deps]
ADOLC_jll = "5f481b30-e4a3-563b-890b-c343462061b6"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
CxxWrap = "0.16"
ADOLC_jll = "1.2.1"
LinearAlgebra = "1.9"
SpecialFunctions = "2.4"
julia = "1.9"
